name: Comment
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
permissions: read-all

jobs:
  build:
    name: Slack
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACKIFY_MARKDOWN: true
          SLACK_MESSAGE: |
            ‚úèÔ∏è [${{ github.event.comment.user.login }}](${{ github.event.comment.html_url }}): ${{ github.event.comment.body }}
            üîÄ ${{ github.event.issue.title }}