name: External link check

on:
  workflow_dispatch: # on demand launches, if needed
  schedule:
    - cron: "5 0 * * 2" # 00:05 on Tuesday, near the dependabot.yml

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: (docs) Check broken HTTP(S) links
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          args: >
            -n -s https -s http --base 'https://docs.tact-lang.org'
            --exclude-path docs/node_modules
            --exclude '\.(?:jpg|png)$'
            docs/README.md './docs/**/*.mdx'
          output: "/dev/stdout"
          fail: true
          failIfEmpty: false

  linkcheck-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: (dev-docs) Check broken HTTP(S) links
        uses: lycheeverse/lychee-action@v2
        id: lychee_dev
        with:
          args: >
            -n -s https -s http
            --exclude-path node_modules --exclude-path docs
            './**/*.md'
          output: "/dev/stdout"
          fail: true
          failIfEmpty: false

  linkcheck-stdlib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: (stdlib) Check broken HTTP(S) links in doc comments
        uses: lycheeverse/lychee-action@v2
        id: lychee_dev
        with:
          args: >
            -n -s https -s http
            './src/stdlib/stdlib/**/*.tact'
          output: "/dev/stdout"
          fail: true
          failIfEmpty: false
