name: Pull request
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: Markdown
          # this might go wrong, because `title` can have arbitrary markdown
          message: |
            ğŸ° [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
            ğŸŒ² ${{ github.repository }}
            ğŸ‘¤ ${{ github.actor }}
            ğŸ”€ ${{ github.event.pull_request.base.label }} <- ${{ github.event.pull_request.head.label }}
