name: Pull request
on:
  pull_request:
    types: [opened, reopened]
permissions: read-all

jobs:
  build:
    name: Slack
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notify
        continue-on-error: true
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACKIFY_MARKDOWN: true
          SLACK_MESSAGE: |
            ğŸ° [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
            ğŸŒ² ${{ github.repository }}
            ğŸ‘¤ ${{ github.actor }}
            ğŸ”€ ${{ github.event.pull_request.base.label }} <- ${{ github.event.pull_request.head.label }}